### PR TITLE
added debouncing of today's energy sensors

### PR DESCRIPTION
**Pull request by patman15**
Hi!

I know you do not want to change the code until the pull-request to core is through, but still to document the enhancement, here it is. This changes solves [the issue](https://github.com/SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant/issues/34) that the inverter restarts "daily production" in case there is power outage or not enough sunlight to keep the inverter awake. Value do increase until midnight and then fall back to zero. Still values are not available when the inverter is offline, so behaviour is similar to before the change.
Tested in my setup.
Maybe you find it useful, it helped me a lot for the energy statistics which were otherwise messed up.

### CODE REVIEW

**Comment by mawoka-myblock** [comment]
Hey, thank you very much. I've reworked most of the code to use SensorDescriptions in the PR (https://github.com/home-assistant/core/pull/114531), so this won't be applicable 1:1. Because of that, I'll keep this PR open, as I just want to archive this repo, but at HA's pace regarding PRs, this will be in ~2 years.

**Comment by patman15** [comment]
Do you want me to switch over to the code of the PR and fix it there as well?

**Comment by mawoka-myblock** [comment]
If you want, sure! Can you just push to a PR like that?

**Comment by mawoka-myblock** [comment]
The integration is now merged into HA core. Feel free to create a PR there.

**Pull request closed without merging**
